export const GET_ALL_BREEDS = 'GET_ALL_BREEDS'
export const GET_BREED_BY_NAME = 'GET_BREED_BY_NAME'

export const START_FETCHING = 'START_FETCHING'
export const START_POSTING = 'START_POSTING'

export const GET_TEMPERAMENTS = 'GET_TEMPERAMENTS'

export const CREATE_BREED = 'CREATE_BREED'
